export type KnowledgeRelationKind =
    | "produces"
    | "uses-component"
    | "uses-tool"
    | "requires-quality"
    | "requires-skill"
    | "requires-proficiency"
    | "learned-from"
    | "uses-requirement"
    | "provides-quality"
    | "uncrafts-item"
    | "recovers-component"
    | "applies-mapgen"
    | "provides-camp-feature"
    | "triggers-eoc";
